import type { AppItem } from "./store";

const DEMO_APPS: Array<Omit<AppItem, "id" | "createdAt" | "lastUpdated">> = [
  {
    name: "WhatsApp Messenger",
    description: "WhatsApp from Meta is a FREE messaging and video calling app. It's used by over 2B people in more than 180 countries. It's simple, reliable, and private, so you can easily keep in touch with your friends and family.\n\nSend private messages and calls to your friends and family.",
    category: "Apps",
    iconURL: "https://play-lh.googleusercontent.com/bYtqbOcTYOlgc6gqZ2rwb8lptHuwlNE75zYJu6Bn076-hTmvd96HH-6v7S0YUAAJXoJN=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/whatsapp.apk",
    fileSize: "67 MB",
    version: "2.24.25.78",
    status: "approved",
    downloads: 5000000000,
    rating: 4.2,
    createdBy: "demo",
    createdByName: "Meta Platforms, Inc.",
    createdByPhone: "+1-650-543-4800",
    whatsNew: "• Bug fixes and performance improvements\n• New emoji reactions\n• Improved voice message quality",
    permissions: ["Camera", "Microphone", "Contacts", "Storage", "Location", "Phone"],
    license: "Free",
    privacyPolicyURL: "https://www.whatsapp.com/legal/privacy-policy",
    contentRating: "Everyone",
    requiresAndroid: "5.0 and up",
    installs: "5,000,000,000+",
    containsAds: false,
    inAppPurchases: false,
    dataSafety: { dataShared: "No data shared with third parties", dataCollected: "Personal info, Messages, Photos", securityPractices: "Data is encrypted in transit." },
  },
  {
    name: "Telegram",
    description: "Telegram is a messaging app with a focus on speed and security. You can use Telegram on all your devices at the same time.\n\nSend messages, photos, videos and files of any type.",
    category: "Apps",
    iconURL: "https://play-lh.googleusercontent.com/ZU9cSsyIJZo6Oy7HTHiEPwZg0m2Crep-d5ZrfajqBBGGDLyUZjjo3GVOvMpz3BD__iG4=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/telegram.apk",
    fileSize: "40 MB",
    version: "11.2.0",
    status: "approved",
    downloads: 1000000000,
    rating: 4.5,
    createdBy: "demo",
    createdByName: "Telegram FZ-LLC",
    createdByPhone: "+971-4-123-4567",
    whatsNew: "• Stories for channels\n• Giveaways and gifts\n• Color themes for messages",
    permissions: ["Camera", "Microphone", "Contacts", "Storage", "Location"],
    license: "Free",
    privacyPolicyURL: "https://telegram.org/privacy",
    contentRating: "Everyone 10+",
    requiresAndroid: "6.0 and up",
    installs: "1,000,000,000+",
    containsAds: false,
    inAppPurchases: true,
    dataSafety: { dataShared: "No data shared with third parties", dataCollected: "Personal info, Messages", securityPractices: "Data is encrypted in transit." },
  },
  {
    name: "Instagram",
    description: "Bringing you closer to the people and things you love. Instagram from Meta is a free photo and video sharing app.\n\nConnect with friends, share what you're up to, or see what's new from others.",
    category: "Apps",
    iconURL: "https://play-lh.googleusercontent.com/VRMWkE5p3CkWhJs6nv-9ZsLAs1QOg5ob1_3qg-rckwYW7yp1fMrYZqnEFpk0IoVP4LM=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/instagram.apk",
    fileSize: "75 MB",
    version: "340.0.0.0",
    status: "approved",
    downloads: 5000000000,
    rating: 4.0,
    createdBy: "demo",
    createdByName: "Meta Platforms, Inc.",
    createdByPhone: "+1-650-543-4800",
    whatsNew: "• Bug fixes\n• Performance improvements\n• New Reels editing tools",
    permissions: ["Camera", "Microphone", "Contacts", "Storage", "Location"],
    license: "Free",
    privacyPolicyURL: "https://privacycenter.instagram.com/policy",
    contentRating: "Teen",
    requiresAndroid: "8.0 and up",
    installs: "5,000,000,000+",
    containsAds: true,
    inAppPurchases: true,
    dataSafety: { dataShared: "Personal info may be shared", dataCollected: "Personal info, Location, Photos", securityPractices: "Data is encrypted in transit." },
  },
  {
    name: "Subway Surfers",
    description: "DASH as fast as you can! DODGE the oncoming trains!\n\n★ Grind trains with your cool crew!\n★ Colorful and vivid HD graphics!\n★ Hoverboard Surfing!",
    category: "Games",
    iconURL: "https://play-lh.googleusercontent.com/cEkiV3sMij_L6MPSC8WIiCgaGwm4MJdFe7CcLaR2s13hD5VRXlsqXCJ3feCUILJP3g=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/subway.apk",
    fileSize: "185 MB",
    version: "3.36.0",
    status: "approved",
    downloads: 2000000000,
    rating: 4.3,
    createdBy: "demo",
    createdByName: "SYBO Games",
    createdByPhone: "+45-70-25-25-25",
    whatsNew: "• New city update!\n• New characters and boards\n• Seasonal events",
    permissions: ["Storage", "Internet"],
    license: "Free",
    privacyPolicyURL: "https://sfruns.com/privacy",
    contentRating: "Everyone",
    requiresAndroid: "5.0 and up",
    installs: "2,000,000,000+",
    containsAds: true,
    inAppPurchases: true,
    dataSafety: { dataShared: "App activity may be shared for advertising", dataCollected: "Personal info, Device info", securityPractices: "Data is encrypted in transit." },
  },
  {
    name: "Google Classroom",
    description: "Classroom helps students and teachers organize assignments, boost collaboration, and foster better communication.",
    category: "Education",
    iconURL: "https://play-lh.googleusercontent.com/w0s3au7cWptVf648ChCUP7sW6uzdwGFkmEOYTiMIhEOqaJP9sPX3jxJf6MkjURDmOmc=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/classroom.apk",
    fileSize: "35 MB",
    version: "9.0.15",
    status: "approved",
    downloads: 500000000,
    rating: 3.9,
    createdBy: "demo",
    createdByName: "Google LLC",
    createdByPhone: "+1-650-253-0000",
    whatsNew: "• New grading features\n• Performance improvements",
    permissions: ["Camera", "Storage", "Contacts"],
    license: "Free",
    privacyPolicyURL: "https://policies.google.com/privacy",
    contentRating: "Everyone",
    requiresAndroid: "6.0 and up",
    installs: "500,000,000+",
    containsAds: false,
    inAppPurchases: false,
    dataSafety: { dataShared: "No data shared with third parties", dataCollected: "Personal info, App activity", securityPractices: "Data is encrypted in transit. You can request that data be deleted." },
  },
  {
    name: "Files by Google",
    description: "Files by Google is a file management app that helps you free up space, find files faster, and share them offline.",
    category: "Tools",
    iconURL: "https://play-lh.googleusercontent.com/JwcMEhRpONbQhqAB4of6Tu8-aBOjDSxUX5GA12LoP7cw1WIBz3GAdLODtelxaDIEMIQ=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/files.apk",
    fileSize: "28 MB",
    version: "1.1420.0",
    status: "approved",
    downloads: 1000000000,
    rating: 4.6,
    createdBy: "demo",
    createdByName: "Google LLC",
    createdByPhone: "+1-650-253-0000",
    whatsNew: "• Improved file sharing\n• New cleaning suggestions\n• Bug fixes",
    permissions: ["Storage", "Camera"],
    license: "Free",
    privacyPolicyURL: "https://policies.google.com/privacy",
    contentRating: "Everyone",
    requiresAndroid: "8.0 and up",
    installs: "1,000,000,000+",
    containsAds: true,
    inAppPurchases: false,
    dataSafety: { dataShared: "No data shared with third parties", dataCollected: "App activity, Device info", securityPractices: "Data is encrypted in transit." },
  },
  {
    name: "Clash of Clans",
    description: "Join millions of players worldwide as you build your village, raise a clan, and compete in epic Clan Wars!",
    category: "Games",
    iconURL: "https://play-lh.googleusercontent.com/LByrur1mTmPeNr0ljI-uAUcct1s_1b1ywg3JnUqg8DJrrHcOEczYQCQ9p1WNxGdKjQ=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/coc.apk",
    fileSize: "290 MB",
    version: "16.386.14",
    status: "approved",
    downloads: 500000000,
    rating: 4.5,
    createdBy: "demo",
    createdByName: "Supercell",
    createdByPhone: "+358-9-4245-2000",
    whatsNew: "• New Town Hall level\n• Balance changes\n• New troops and spells",
    permissions: ["Storage", "Internet", "Phone"],
    license: "Free",
    privacyPolicyURL: "https://supercell.com/en/privacy-policy/",
    contentRating: "Everyone 10+",
    requiresAndroid: "5.0 and up",
    installs: "500,000,000+",
    containsAds: false,
    inAppPurchases: true,
    dataSafety: { dataShared: "App activity may be shared for analytics", dataCollected: "Personal info, Financial info", securityPractices: "Data is encrypted in transit." },
  },
  {
    name: "Duolingo",
    description: "Learn a new language with the world's most-downloaded education app! Fun, free, and effective.\n\n• 40+ languages\n• Quick bite-sized lessons\n• Proven to work!",
    category: "Education",
    iconURL: "https://play-lh.googleusercontent.com/rIY2LyEQm0KTBcaLNIq1pBjjdg0js8VW0m3LxhjJlHBMsHKV6IFvcbLFfpQPWlJgJA=w240-h480-rw",
    screenshots: [],
    fileURL: "https://example.com/duolingo.apk",
    fileSize: "55 MB",
    version: "5.142.3",
    status: "approved",
    downloads: 500000000,
    rating: 4.7,
    createdBy: "demo",
    createdByName: "Duolingo",
    createdByPhone: "+1-412-567-8900",
    whatsNew: "• New language courses\n• Improved speech recognition\n• Performance fixes",
    permissions: ["Microphone", "Storage", "Camera"],
    license: "Free",
    privacyPolicyURL: "https://www.duolingo.com/privacy",
    contentRating: "Everyone",
    requiresAndroid: "8.0 and up",
    installs: "500,000,000+",
    containsAds: true,
    inAppPurchases: true,
    dataSafety: { dataShared: "Personal info may be shared for advertising", dataCollected: "Personal info, App activity", securityPractices: "Data is encrypted in transit." },
  },
];

export function seedDemoData() {
  if (typeof window === "undefined") return;
  const existing = localStorage.getItem("playdock_apps");
  if (existing) {
    try {
      const apps = JSON.parse(existing);
      if (apps.length > 0) return;
    } catch {}
  }

  const now = Date.now();
  const apps = DEMO_APPS.map((app, i) => ({
    ...app,
    id: `demo-${i + 1}`,
    createdAt: now - (i * 86400000),
    lastUpdated: now - (i * 3600000),
  }));

  localStorage.setItem("playdock_apps", JSON.stringify(apps));

  const reviews: Record<string, Array<{ userId: string; userName: string; stars: number; comment: string; date: number }>> = {
    "demo-1": [
      { userId: "r1", userName: "Rahim Ahmed", stars: 5, comment: "Best messaging app! Fast and reliable.", date: now - 86400000 },
      { userId: "r2", userName: "Sara Khan", stars: 4, comment: "Great app but uses a lot of storage.", date: now - 172800000 },
    ],
    "demo-2": [
      { userId: "r4", userName: "Arif Islam", stars: 5, comment: "Much better than WhatsApp for privacy!", date: now - 86400000 },
    ],
    "demo-4": [
      { userId: "r6", userName: "Tanvir Rahman", stars: 5, comment: "Addictive game! My kids love it.", date: now - 86400000 },
    ],
  };
  localStorage.setItem("playdock_reviews", JSON.stringify(reviews));
}
